// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int nTimes = Integer.parseInt(args[0]);
		double greaterCounter = 0;
		double lowerCounter = 0;

		for (int i = 0; i < nTimes; i++) {

			double randomCounter = Math.random();

			if (randomCounter > 0.5) {
				greaterCounter++;
			} else {
				lowerCounter++;
			}
		}

		if (greaterCounter == 0 || lowerCounter == 0) {

			System.out.println("> 0.5: " + (int)greaterCounter + " times\n" +
							"<= 0.5: " + (int)lowerCounter + " times");
		} else {
			double ratio = greaterCounter / lowerCounter;

		System.out.println("> 0.5: " + (int)greaterCounter + " times\n" +
							"<= 0.5: " + (int)lowerCounter + " times\n" +
							"Ratio: " + ratio);
		}
		
	}
}
